#!/usr/bin/env bash
set -Eeu

function generate_pass(){
  for ((i=0;i<${1:-1};i++)) {
    local pass=''
    while [ "${pass}" = '' ]; do
      pass="$(tr -dc '0-9a-z!@#$%^&*()+=_' </dev/urandom | head -c${2:-10} | perl -ne 'print if(/^(?=.*[a-z])(?=.*[0-9])(?=.*[!@#$%^&*()+=_]).*$/)')"
    done
    echo "${pass}"
  }
}
generate_pass "${@}"
